/*
 * File: pci_classes.h
 * 
 * Copyright (c) 2017-2018 Sydney Erickson, John Davis
 * 
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 * 
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef PCI_CLASSES_H
#define PCI_CLASSES_H

//
// PCI class codes.
//
#define PCI_CLASS_NONE				0x00
#define PCI_CLASS_MASS_STORAGE		0x01
#define PCI_CLASS_NETWORK			0x02
#define PCI_CLASS_DISPLAY			0x03
#define PCI_CLASS_MULTIMEDIA		0x04
#define PCI_CLASS_MEMORY			0x05
#define PCI_CLASS_BRIDGE			0x06
#define PCI_CLASS_SIMPLE_COMM		0x07
#define PCI_CLASS_BASE_SYSTEM		0x08
#define PCI_CLASS_INPUT				0x09
#define PCI_CLASS_DOCKING			0x0A
#define PCI_CLASS_PROCESSOR			0x0B
#define PCI_CLASS_SERIAL_BUS		0x0C
#define PCI_CLASS_WIRELESS			0x0D
#define PCI_CLASS_INTELLIGENT_IO	0x0E
#define PCI_CLASS_SATELLITE_COMM	0x0F
#define PCI_CLASS_ENCRYPTION		0x10
#define PCI_CLASS_DATA_ACQUISITION	0x11
#define PCI_CLASS_UNKNOWN			0xFF

//
// Base class 0x00 (no class).
//
#define PCI_SUBCLASS_NONE_ALL_BUT_VGA       0x00
#define PCI_SUBCLASS_NONE_VGA               0x01

//
// Base class 0x01 (mass storage).
//
#define PCI_SUBCLASS_MASS_STORAGE_SCSI      0x00
#define PCI_SUBCLASS_MASS_STORAGE_IDE       0x01
#define PCI_SUBCLASS_MASS_STORAGE_FLOPPY    0x02
#define PCI_SUBCLASS_MASS_STORAGE_IPI       0x03
#define PCI_SUBCLASS_MASS_STORAGE_RAID      0x04
#define PCI_SUBCLASS_MASS_STORAGE_ATA       0x05
#define PCI_SUBCLASS_MASS_STORAGE_SATA      0x06
#define PCI_SUBCLASS_MASS_STORAGE_SAS       0x07
#define PCI_SUBCLASS_MASS_STORAGE_OTHER     0x80

// Interface codes for base class 0x01.
#define PCI_INTERFACE_MASS_STORAGE_ATA_ADMA_SINGLE  0x20
#define PCI_INTERFACE_MASS_STORAGE_ATA_ADMA_CONT    0x30

#define PCI_INTERFACE_MASS_STORAGE_SATA_VENDOR_SPEC 0x00
#define PCI_INTERFACE_MASS_STORAGE_SATA_VENDOR_AHCI 0x01

//
// Base class 0x02 (network).
//
#define PCI_SUBCLASS_NETWORK_ETHERNET       0x00
#define PCI_SUBCLASS_NETWORK_TOKEN_RING     0x01
#define PCI_SUBCLASS_NETWORK_FDDI           0x02
#define PCI_SUBCLASS_NETWORK_ATM            0x03
#define PCI_SUBCLASS_NETWORK_ISDN           0x04
#define PCI_SUBCLASS_NETWORK_WORLDFLIP      0x05
#define PCI_SUBCLASS_NETWORK_PICMG          0x06
#define PCI_SUBCLASS_NETWORK_OTHER          0x80

//
// Base class 0x03 (display).
//
#define PCI_SUBCLASS_DISPLAY_VGA            0x00
#define PCI_SUBCLASS_DISPLAY_XGA            0x01
#define PCI_SUBCLASS_DISPLAY_3D             0x02
#define PCI_SUBCLASS_DISPLAY_OTHER          0x80

// Interface codes for base class 0x03.
#define PCI_INTERFACE_DISPLAY_VGA_VGA       0x00
#define PCI_INTERFACE_DISPLAY_VGA_8514      0x01

//
// Base class 0x04 (multimedia).
//
#define PCI_SUBCLASS_MULTIMEDIA_VIDEO       0x00
#define PCI_SUBCLASS_MULTIMEDIA_AUDIO       0x01
#define PCI_SUBCLASS_MULTIMEDIA_TELEPHONY   0x02
#define PCI_SUBCLASS_MULTIMEDIA_OTHER       0x80

//
// Base class 0x05 (memory).
//
#define PCI_SUBCLASS_MEMORY_RAM             0x00
#define PCI_SUBCLASS_MEMORY_FLASH           0x01
#define PCI_SUBCLASS_MEMORY_OTHER           0x80

//
// Base class 0x06 (bridge).
//
#define PCI_SUBCLASS_BRIDGE_HOST            0x00
#define PCI_SUBCLASS_BRIDGE_ISA             0x01
#define PCI_SUBCLASS_BRIDGE_EISA            0x02
#define PCI_SUBCLASS_BRIDGE_MCA             0x03
#define PCI_SUBCLASS_BRIDGE_PCI             0x04
#define PCI_SUBCLASS_BRIDGE_PCMCIA          0x05
#define PCI_SUBCLASS_BRIDGE_NUBUS           0x06
#define PCI_SUBCLASS_BRIDGE_CARDBUS         0x07
#define PCI_SUBCLASS_BRIDGE_RACEWAY         0x08
#define PCI_SUBCLASS_BRIDGE_PCI_SEMI_TRANS  0x09
#define PCI_SUBCLASS_BRIDGE_INFINIBAND      0x0A
#define PCI_SUBCLASS_BRIDGE_OTHER           0x80

// Interface codes for base class 0x06.
#define PCI_INTERFACE_BRIDGE_PCI_PCI            0x00
#define PCI_INTERFACE_BRIDGE_PCI_SUBTRACT       0x01

#define PCI_INTERFACE_BRIDGE_PCI_SEMI_TRANS_PRI 0x40
#define PCI_INTERFACE_BRIDGE_PCI_SEMI_TRANS_SEC 0x80

//
// Base class 0x07 (simple communications).
//
#define PCI_SUBCLASS_SIMPLE_COMM_SERIAL         0x00
#define PCI_SUBCLASS_SIMPLE_COMM_PARALLEL       0x01
#define PCI_SUBCLASS_SIMPLE_COMM_SERIAL_MULTI   0x02
#define PCI_SUBCLASS_SIMPLE_COMM_MODEM          0x03
#define PCI_SUBCLASS_SIMPLE_COMM_GPIB           0x04
#define PCI_SUBCLASS_SIMPLE_COMM_SMAR_CARD      0x05
#define PCI_SUBCLASS_SIMPLE_COMM_OTHER          0x80

// Interface codes for base class 0x07.
#define PCI_INTERFACE_SIMPLE_COMM_SERIAL_GENERIC    0x00
#define PCI_INTERFACE_SIMPLE_COMM_SERIAL_16450      0x01
#define PCI_INTERFACE_SIMPLE_COMM_SERIAL_16550      0x02
#define PCI_INTERFACE_SIMPLE_COMM_SERIAL_16650      0x03
#define PCI_INTERFACE_SIMPLE_COMM_SERIAL_16750      0x04
#define PCI_INTERFACE_SIMPLE_COMM_SERIAL_16850      0x05
#define PCI_INTERFACE_SIMPLE_COMM_SERIAL_16950      0x06

#define PCI_INTERFACE_SIMPLE_COMM_PARALLEL_NORMAL               0x00
#define PCI_INTERFACE_SIMPLE_COMM_PARALLEL_BIDIR                0x01
#define PCI_INTERFACE_SIMPLE_COMM_PARALLEL_ECP                  0x02
#define PCI_INTERFACE_SIMPLE_COMM_PARALLEL_IEEE1284_CONTROLLER  0x03
#define PCI_INTERFACE_SIMPLE_COMM_PARALLEL_IEEE1284_DEVICE      0xFE

#define PCI_INTERFACE_SIMPLE_COMM_MODEM_GENERIC     0x00
#define PCI_INTERFACE_SIMPLE_COMM_MODEM_HAYES_16450 0x01
#define PCI_INTERFACE_SIMPLE_COMM_MODEM_HAYES_16550 0x02
#define PCI_INTERFACE_SIMPLE_COMM_MODEM_HAYES_16650 0x03
#define PCI_INTERFACE_SIMPLE_COMM_MODEM_HAYES_16750 0x04

//
// Base class 0x08 (base system).
//
#define PCI_SUBCLASS_BASE_SYSTEM_PIC            0x00
#define PCI_SUBCLASS_BASE_SYSTEM_DMA            0x01
#define PCI_SUBCLASS_BASE_SYSTEM_TIMER          0x02
#define PCI_SUBCLASS_BASE_SYSTEM_RTC            0x03
#define PCI_SUBCLASS_BASE_SYSTEM_PCI_HOTPLUG    0x04
#define PCI_SUBCLASS_BASE_SYSTEM_SD_HOST        0x05
#define PCI_SUBCLASS_BASE_SYSTEM_OTHER          0x80

// Interface codes for base class 0x08.
#define PCI_INTERFACE_BASE_SYSTEM_PIC_GENERIC   0x00
#define PCI_INTERFACE_BASE_SYSTEM_PIC_ISA       0x01
#define PCI_INTERFACE_BASE_SYSTEM_PIC_EISA      0x02
#define PCI_INTERFACE_BASE_SYSTEM_PIC_IOAPIC    0x10
#define PCI_INTERFACE_BASE_SYSTEM_PIC_IOXAPIC   0x20

#define PCI_INTERFACE_BASE_SYSTEM_DMA_GENERIC   0x00
#define PCI_INTERFACE_BASE_SYSTEM_DMA_ISA       0x01
#define PCI_INTERFACE_BASE_SYSTEM_DMA_EISA      0x02

#define PCI_INTERFACE_BASE_SYSTEM_TIMER_GENERIC 0x00
#define PCI_INTERFACE_BASE_SYSTEM_TIMER_ISA     0x01
#define PCI_INTERFACE_BASE_SYSTEM_TIMER_EISA    0x02

#define PCI_INTERFACE_BASE_SYSTEM_RTC_GENERIC   0x00
#define PCI_INTERFACE_BASE_SYSTEM_RTC_ISA       0x01

//
// Base class 0x09 (input).
//
#define PCI_SUBCLASS_INPUT_KEYBOARD         0x00
#define PCI_SUBCLASS_INPUT_DIGITIZER        0x01
#define PCI_SUBCLASS_INPUT_MOUSE            0x02
#define PCI_SUBCLASS_INPUT_SCANNER          0x03
#define PCI_SUBCLASS_INPUT_GAMEPORT         0x04
#define PCI_SUBCLASS_INPUT_OTHER            0x80

// Interface codes for base class 0x09.
#define PCI_INTERFACE_INPUT_GAMEPORT_GENERIC    0x00
#define PCI_INTERFACE_INPUT_GAMEPORT_OTHER      0x10

//
// Base class 0x0A (docking).
//
#define PCI_SUBCLASS_DOCKING_GENERIC        0x00
#define PCI_SUBCLASS_DOCKING_OTHER          0x80

//
// Base class 0x0B (processor).
//
#define PCI_SUBCLASS_PROCESSOR_386          0x00
#define PCI_SUBCLASS_PROCESSOR_486          0x01
#define PCI_SUBCLASS_PROCESSOR_PENTIUM      0x02
#define PCI_SUBCLASS_PROCESSOR_ALPHA        0x10
#define PCI_SUBCLASS_PROCESSOR_POWERPC      0x20
#define PCI_SUBCLASS_PROCESSOR_MIPS         0x30
#define PCI_SUBCLASS_PROCESSOR_COPROCESSOR  0x40

//
// Base class 0x0C (serial bus).
//
#define PCI_SUBCLASS_SERIAL_BUS_FIREWIRE    0x00
#define PCI_SUBCLASS_SERIAL_BUS_ACCESS      0x01
#define PCI_SUBCLASS_SERIAL_BUS_SSA         0x02
#define PCI_SUBCLASS_SERIAL_BUS_USB         0x03
#define PCI_SUBCLASS_SERIAL_BUS_FIBRE       0x04
#define PCI_SUBCLASS_SERIAL_BUS_SMBUS       0x05
#define PCI_SUBCLASS_SERIAL_BUS_INFINIBAND  0x06
#define PCI_SUBCLASS_SERIAL_BUS_IPMI        0x07
#define PCI_SUBCLASS_SERIAL_BUS_SERCOS      0x08
#define PCI_SUBCLASS_SERIAL_BUS_CAN         0x09

// Interface codes for base class 0x0C.
#define PCI_INTERFACE_SERIAL_BUS_FIREWIRE_FIREWIRE  0x00
#define PCI_INTERFACE_SERIAL_BUS_FIREWIRE_OHCI      0x10

#define PCI_INTERFACE_SERIAL_BUS_USB_UHCI   0x00
#define PCI_INTERFACE_SERIAL_BUS_USB_OHCI   0x10
#define PCI_INTERFACE_SERIAL_BUS_USB_EHCI   0x20
#define PCI_INTERFACE_SERIAL_BUS_USB_OTHER  0x80
#define PCI_INTERFACE_SERIAL_BUS_USB_DEVICE 0xFE

#define PCI_INTERFACE_SERIAL_BUS_IPMI_SMIC  0x00
#define PCI_INTERFACE_SERIAL_BUS_IPMI_KYBD  0x01
#define PCI_INTERFACE_SERIAL_BUS_IPMI_BLOCK 0x02

//
// Base class 0x0D (wireless).
//
#define PCI_SUBCLASS_WIRELESS_IRDA          0x00
#define PCI_SUBCLASS_WIRELESS_CONSUME_IR    0x01
#define PCI_SUBCLASS_WIRELESS_RF            0x10
#define PCI_SUBCLASS_WIRELESS_BLUETOOTH     0x11
#define PCI_SUBCLASS_WIRELESS_BROADBAND     0x12
#define PCI_SUBCLASS_WIRELESS_WIFI_5GHZ     0x20
#define PCI_SUBCLASS_WIRELESS_WIFI_24GHZ    0x21
#define PCI_SUBCLASS_WIRELESS_OTHER         0x80

//
// Base class 0x0E (intelligent I/O).
//
#define PCI_SUBCLASS_INTELLIGENT_IO_I20     0x00

//
// Base class 0x0F (satellite).
//
#define PCI_SUBCLASS_SATELLITE_COMM_TV      0x01
#define PCI_SUBCLASS_SATELLITE_COMM_AUDIO   0x02
#define PCI_SUBCLASS_SATELLITE_COMM_VOICE   0x03
#define PCI_SUBCLASS_SATELLITE_COMM_DATA    0x04

//
// Base class 0x10 (encryption).
//
#define PCI_SUBCLASS_ENCRYPTION_NETWORK         0x00
#define PCI_SUBCLASS_ENCRYPTION_ENTERTAINMENT   0x10
#define PCI_SUBCLASS_ENCRYPTION_OTHER           0x80

//
// Base class 0x11 (data acquistion).
//
#define PCI_SUBCLASS_DATA_ACQUISITION_DPIO      0x00
#define PCI_SUBCLASS_DATA_ACQUISITION_PERF      0x01
#define PCI_SUBCLASS_DATA_ACQUISITION_SYNC      0x10
#define PCI_SUBCLASS_DATA_ACQUISITION_MANGEMENT 0x20
#define PCI_SUBCLASS_DATA_ACQUISITION_OTHER     0x80

#endif
